[package]
name = "jaeymo/wrapper"
description = "Manages instantiating objects from tagged Instances"
version = "0.2.7"
license = "MIT"
authors = ["jaeymo"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
trove = "sleitnick/trove@1.5.1"
general-util = "jaeymo/general-util@0.3.0"