[package]
name = "jaey-dev/wrapper"
description = "Manages class lifecycles from tagged Instances"
version = "0.1.1"
license = "MIT"
authors = ["Jaeymo"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@1.5.1"