[package]
name = "jaeymo/viewer"
description = "Module containing observer methods"
version = "0.1.0"
license = "MIT"
authors = ["jaeymo"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"