[package]
name = "jaey-dev/generalutil"
description = "Simple utility functions"
license = "MIT"
authors = ["Jaeymo"]
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"