[package]
name = "jaey-dev/general-util"
description = "Simple utility functions"
license = "MIT"
authors = ["Jaeymo"]
version = "0.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"