[package]
name = "jaey-dev/betteranimation"
description = "Simplifies client-side animation management"
version = "0.1.0"
license = "MIT"
authors = ["Jaeymo"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"